language: node_js
node_js:
- '6'
cache:
  directories:
  - node_modules
script: echo "No tests";
before_deploy:
  - node generate.js
deploy:
  provider: pages
  skip_cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
